/* 第 0 幕（无标题）· seg_000_opening
 * 触发条件：新游戏第一次进入世界时立即触发
 *   → main.js startNew() 会把 G.day 设为 0，本片段 condition 匹配
 *   → 播完后 afterPlayed 把 day 推进到 1，玩家正式进入第一天
 *
 * 元指令使用：
 *   【屏幕抖动】 ×2（头部剧痛）
 *   【屏幕闪白】 ×3（回忆开始 / 穿越瞬间 / 回忆结束）
 *   【回忆开始】 切灰白背景
 *   【回忆结束】 切回正常
 *   【轻微抖动】（杨一帆砸落，不要太强烈）
 *   【act:第一幕 分道扬镳】结尾升幕标题
 */
export default {
  id: 'main_act00_seg000',
  act: 0,
  title: '第0幕·醒来',

  condition: ()=> G && G.day===0 && !G.records?.mainStoryDone?.['main_act00_seg000'],

  body: [
    // —— 帐篷内醒来 ——
    { speaker: null, html: '<p>我做了一个好长好长的梦。</p>' },
    { speaker: null, html: '<p>在梦里，我成为了击败魔王的勇者。</p>' },
    { speaker: null, html: '<p>将剑插入魔王心脏的那一刻，我意识到这只是一场幻梦。</p>' },
    { speaker: null, html: '<p>醒来吧。</p>' },
    { speaker: null, html: '<p>醒来吧。</p>' },
    { speaker: null, html: '<p>我听见自己颤动的心跳声。</p>' },
    { speaker: null, html: '<p>我听见身旁他人微弱的呼吸声。</p>' },
    { speaker: null, html: '<p>我听见不远处篝火燃烧的"噼啪"声……</p>' },
    { speaker: '？？？', html: '<p>你醒了？</p>' },
    { speaker: null, html: '<p>我睁开眼，艰难地扭头观察了一圈。</p>' },
    { speaker: null, html: '<p>一个简陋的自制帐篷。身旁只有一位少女正端详着我。</p>' },
    { speaker: '？？？', html: '<p>你应该，还记得我吧？</p>' },
    { speaker: null, html: '<p>记得？</p>' },
    { speaker: null, html: '<p>记得什么……</p>' },
    { speaker: null, html: '<p>头部传来一阵刺痛。【屏幕抖动】</p>' },
    { speaker: null, html: '<p>噢不不，我只是暂且睡迷糊了，说不定问点别的事就想起来了。</p>' },
    { speaker: '我', html: '<p>这里是哪，我怎么在这睡着了？</p>' },
    { speaker: '？？？', html: '<p>我也不知道这地叫什么，先叫它异世界好了。</p>' },
    { speaker: '我', html: '<p>异世……呃！</p>' },
    { speaker: null, html: '<p>刺痛加剧了！【屏幕抖动】</p>' },
    { speaker: '？？？', html: '<p>你还好吧？！先平静下来？</p>' },
    { speaker: '？？？', html: '<p>我们都是穿越过来的。你慢慢回想，能想起来吗？</p>' },
    { speaker: null, html: '<p>我痛苦地捂住额头。</p>' },
    { speaker: null, html: '<p>如果我非得认识这位少女的话，那应该是、应该是……应该是！</p>' },
    { speaker: null, html: '<p>痛苦与恍惚中，我似乎取回了一部分记忆。</p>' },
    { speaker: null, html: '<p>我是……余默，正担任……本次五一晚会故事剧的编导。</p>' },

    // —— 闪白 + 回忆（灰白背景）——
    { speaker: null, html: '<p>【屏幕闪白】</p>' },
    { speaker: null, html: '<p>【回忆开始】</p>' },

    // —— 回忆片段 ——
    { speaker: '我', html: '<p>雨太大了来不了？……不不，没事，排练而已。</p>' },
    { speaker: '叶唯安', html: '<p>灰白没空？</p>' },
    { speaker: null, html: '<p>我放下手机，叹了口气。</p>' },
    { speaker: '夏阳', html: '<p>那我和空气演对手戏吗？</p>' },
    { speaker: '叶唯安', html: '<p>你可以把我当做魔王。想想，在击败了最后一个魔王守卫后，身后的同伴突然亮起了血条……</p>' },
    { speaker: '夏阳', html: '<p>也只能这样办了……</p>' },
    { speaker: '夏阳', html: '<p>老家伙！我不过化作了人形便不认识我了吗？那这凤凰真火你可还记得？</p>' },
    { speaker: '叶唯安', html: '<p>记得。</p>' },
    { speaker: '夏阳', html: '<p>……</p>' },
    { speaker: '叶唯安', html: '<p>那……不记得？</p>' },
    { speaker: '夏阳', html: '<p>啊啊啊，你又不知道魔王的台词，跟你演和唱独角戏没有区别啊！</p>' },
    { speaker: '夏阳', html: '<p>cut、cut。余默，让其他人先上台练后面的剧情吧。</p>' },
    { speaker: null, html: '<p>我扶了扶额，比了个ok的手势，往台下走去。</p>' },
    { speaker: null, html: '<p>陆悠悠正在后台整理道具。见我来了，她对着空气摆出了一个拉弓的姿势。</p>' },
    { speaker: '陆悠悠', html: '<p>你应当，畏惧我的箭！</p>' },
    { speaker: '我', html: '<p>这是第二幕的台词对吧。可是，你的弓呢？</p>' },
    { speaker: '陆悠悠', html: '<p>是啊～我的弓呢？</p>' },
    { speaker: null, html: '<p>被她反问后，我突然想起，还有一批道具没送到。</p>' },
    { speaker: '陆悠悠', html: '<p>大后天就要演出了，但我数了一遍，还有3份道具没来，4份道具数量有缺，还有夏阳的凤凰翅膀，昨天收进箱子的时候被折断了。</p>' },
    { speaker: '我', html: '<p>我马上就催。</p>' },
    { speaker: '陆悠悠', html: '<p>待会吧。现在我建议你去休息室看看为妙。我听见刚才有争吵声。</p>' },
    { speaker: null, html: '<p>我推开休息室的门。许泠朦正坐在靠门的化妆台前，宋梦雨站在她身后捏着她的脸。</p>' },
    { speaker: '宋梦雨', html: '<p>说起来，我的名字也有水，我俩角色互换也不是不可？</p>' },
    { speaker: '许泠朦', html: '<p>我可不想重新背一份新稿子啊！</p>' },
    { speaker: '我', html: '<p>是你们俩在吵架？</p>' },
    { speaker: '宋梦雨', html: '<p>没。我只是看见那俩人拌嘴之后，有感而发。</p>' },
    { speaker: '宋梦雨', html: '<p>我猜你想找的，是那边俩位。</p>' },
    { speaker: null, html: '<p>我循着她指着的方向望去，杨一帆和潘天宇正在角落里争得面红耳赤。</p>' },
    { speaker: '我', html: '<p>吵什么？</p>' },
    { speaker: '潘天宇', html: '<p>只是请他少点对别人妄加揣测，有这闲心不如把自己的事做好。</p>' },
    { speaker: '杨一帆', html: '<p>呵，你真有意思，这本来也不是我的角色吧？</p>' },
    { speaker: null, html: '<p>我想我知道他们在争吵什么。前天，老师临时指派我作为编导。杨一帆原本饰演魔王，改为顶替我饰演点石成金的矮人。而新来的灰白学妹扮演了魔王。</p>' },
    { speaker: '我', html: '<p>临时换了你的角色我很抱歉，可那也是计划之外不得不——</p>' },
    { speaker: '杨一帆', html: '<p>住嘴。</p>' },
    { speaker: '杨一帆', html: '<p>你再怎么唯唯诺诺地解释，也掩盖不了你傲慢自私。</p>' },
    { speaker: null, html: '<p>傲慢？自私？我？</p>' },
    { speaker: '潘天宇', html: '<p>喂喂，话别说太过火了！</p>' },
    { speaker: '杨一帆', html: '<p>和稀泥的就别来沾边。</p>' },
    { speaker: '杨一帆', html: '<p>我问你，凭什么换掉我的魔王？凭什么迁就新来的人改动剧本？！</p>' },
    { speaker: '我', html: '<p>我也不过是被临时指派来做编导。演员变动了，角色分配就得跟着变，我已经尽力安排了！</p>' },
    { speaker: null, html: '<p>窗外的暴雨噼里啪啦砸在玻璃上，沉闷的雷声闷滚而来，压得人喘不过气。</p>' },
    { speaker: null, html: '<p>许泠朦和宋梦雨停止了嬉闹。夏阳、叶唯安、陆悠悠也恰好从舞台回来。</p>' },
    { speaker: null, html: '<p>没法收场了啊。</p>' },
    { speaker: null, html: '<p>为什么会这样呢？</p>' },
    { speaker: '杨一帆', html: '<p>你只委屈自己尽力了。有没有想过，你所谓的尽力其实是在带给其他人烦恼呢？</p>' },
    { speaker: null, html: '<p>所有人默默地看向我，却没有人第一时间为我反驳杨一帆的话。</p>' },
    { speaker: '许泠朦', html: '<p>你们先别吵了。雨好像飘进来了。</p>' },
    { speaker: '夏阳', html: '<p>窗户明明关着啊？</p>' },
    { speaker: null, html: '<p>够了，别转移话题……如果你们都这样认为……</p>' },
    { speaker: null, html: '<p>我突然发力，一把拽住杨一帆的衣领。</p>' },
    { speaker: '杨一帆', html: '<p>啧！</p>' },
    { speaker: '潘天宇', html: '<p>余默！等——</p>' },
    { speaker: '我', html: '<p>呵……呵呵呵……！</p>' },
    { speaker: '我', html: '<p>是我，把你们这几个稀奇古怪的人组在一起；是我，被调到编导之后又是拉新人又是改剧本；是我，没完没了地整理道具还要安排场地……</p>' },
    { speaker: '我', html: '<p>没了我你们根本站不到这里，没了我一切只会变得更糟！天命注定的勇者是我也只能是我！</p>' },
    { speaker: null, html: '<p>【屏幕闪白】</p>' },
    { speaker: null, html: '<p>正当我不顾失态宣泄情绪时，一道白光猝不及防地在我眼前炸开！</p>' },
    { speaker: null, html: '<p>一股烧焦的痛感袭来，意识瞬间模糊……</p>' },
    { speaker: null, html: '<p>众人的惊呼……</p>' },
    { speaker: null, html: '<p>紧随其后的惊雷声……</p>' },
    { speaker: '潘天宇', html: '<p>闪电怎么会劈在屋子里！</p>' },
    { speaker: '夏阳', html: '<p>雨全都进来了，这太诡异了！</p>' },
    { speaker: null, html: '<p>意识彻底沉入黑暗之前，我听见的最后一句话是叶唯安的——"雨有问题"。</p>' },

    // —— 闪回结束 ——
    { speaker: null, html: '<p>【屏幕闪白】</p>' },
    { speaker: null, html: '<p>【回忆结束】</p>' },

    // —— 回到异世界 ——
    { speaker: null, html: '<p>滋——哗啦！我的回忆如同老旧的DVD一般——断片了。</p>' },
    { speaker: null, html: '<p>我必须坦率地承认：我失忆了。</p>' },
    { speaker: null, html: '<p>我只能回想起穿越前的一小节。</p>' },
    { speaker: null, html: '<p>但凭借残存的记忆还是能认出眼前这个忧虑地望着我的少女正是许泠朦。</p>' },
    { speaker: '我', html: '<p>其实我……</p>' },
    { speaker: null, html: '<p>话到嘴边，却被一阵急促的脚步声打断。</p>' },
    { speaker: null, html: '<p>叶唯安掀开了帐篷，他身后是紧张兮兮的夏阳。</p>' },
    { speaker: '叶唯安', html: '<p>啊，你醒了。</p>' },
    { speaker: '夏阳', html: '<p>余默，你终于醒啦？</p>' },
    { speaker: '叶唯安', html: '<p>泠朦，你下午有见过杨一帆吗？</p>' },
    { speaker: null, html: '<p>听起来，有比我昏迷更紧急的事？</p>' },
    { speaker: '许泠朦', html: '<p>早上出门之后，就没见过他了。</p>' },
    { speaker: '许泠朦', html: '<p>他和夏阳一块去钓鱼的吧？</p>' },
    { speaker: '夏阳', html: '<p>那家伙啊，下午说水壶落在营地了要回去取。然后一下午没回来。</p>' },
    { speaker: '夏阳', html: '<p>我原本以为他又在找借口偷懒而已……</p>' },
    { speaker: '叶唯安', html: '<p>我回来路上遇见夏阳，我俩找了一路，没见到人影。</p>' },
    { speaker: '叶唯安', html: '<p>现在看来也不在营地。</p>' },
    { speaker: '许泠朦', html: '<p>……我和你们去周围找一圈。</p>' },
    { speaker: '我', html: '<p>我也和你们一起。</p>' },
    { speaker: '叶唯安', html: '<p>呃……你的身体，不要紧么？</p>' },
    { speaker: '夏阳', html: '<p>你还是躺好吧！</p>' },
    { speaker: null, html: '<p>最终他们让我呆着别动，但我还是挪到了帐篷外边坐着。</p>' },
    { speaker: null, html: '<p>我试着烤了一条夏阳带回的鱼，但只是勉强能吃的水平。</p>' },
    { speaker: null, html: '<p>毕竟我没有野外生存的经验。还是等其他人回来好了……</p>' },
    { speaker: null, html: '<p>等啊等，等到小溪的水面上也不见夕阳的倒影，等到奇形异状的大鸟也"吱吱呀呀"地归了巢，他们一个个神色凝重地回来了。</p>' },
    { speaker: '叶唯安', html: '<p>还是找不到吗？</p>' },
    { speaker: '夏阳', html: '<p>都是我不好！我该早点去找他的。</p>' },
    { speaker: '宋梦雨', html: '<p>不是你的错。都知道他是爱偷懒的性子，谁知道他这回竟然……</p>' },
    { speaker: '陆悠悠', html: '<p>大家，饭总归还是要吃的吧？别忘了还有一个刚醒来的伤员啊。</p>' },
    { speaker: null, html: '<p>于是，陆悠悠负责烤鱼，其余人负责处理肉类和一些野果。</p>' },
    { speaker: null, html: '<p>说是晚饭，每个人能分得的不过半条鱼和几个果子。仅仅是饿不死而已。</p>' },
    { speaker: null, html: '<p>天完全暗下去了，连营地前方的巨树的轮廓也看不清了，只有篝火在无垠的黑暗中愈发亮眼。</p>' },
    { speaker: null, html: '<p>大家围坐一圈，看营火炊烟，看星空点点，本该是有趣的。</p>' },
    { speaker: null, html: '<p>可仅存的那一段并不愉快的记忆还萦绕在我心头。</p>' },
    { speaker: null, html: '<p>"噼啪……"篝火发出细微声响。</p>' },
    { speaker: '许泠朦', html: '<p>刚才太急，没来得及和你细说。</p>' },
    { speaker: '许泠朦', html: '<p>被那奇怪的雨淋湿后，我们全都失去了意识，醒来就在这了。</p>' },
    { speaker: '许泠朦', html: '<p>从穿越过来以后，你的伤势不重，却已经昏迷了整整一天。</p>' },
    { speaker: '许泠朦', html: '<p>之前的事，就忘了吧。一帆他说等你醒了要给你道歉。这是一切重新开始的契机呀～</p>' },
    { speaker: '许泠朦', html: '<p>还是聊点好消息吧——我们每个人突然间都学会了魔法。</p>' },
    { speaker: '夏阳', html: '<p>对对。你看——</p>' },
    { speaker: null, html: '<p>夏阳的手上跳动着一簇细小的球状火焰。</p>' },
    { speaker: '我', html: '<p>这……不烫？</p>' },
    { speaker: null, html: '<p>夏阳摇摇头，手掌一撇，把火球扔进了篝火中。</p>' },
    { speaker: '夏阳', html: '<p>我摸着没感觉。但你肯定不会想碰到它的。</p>' },
    { speaker: '宋梦雨', html: '<p>巧合的是，我们获得的魔法，和我们表演的角色全都对应上了。会有这么巧吗？</p>' },
    { speaker: '我', html: '<p>别管巧不巧合，会魔法肯定是天大的好事哎。</p>' },
    { speaker: null, html: '<p>我想起了表演的剧本——七人组成勇者小队，讨伐了魔王。</p>' },
    { speaker: null, html: '<p>"滋滋……噼啪……"</p>' },
    { speaker: '我', html: '<p>等等，你们有没有听见什么声音？</p>' },
    { speaker: '陆悠悠', html: '<p>该不会烧到上面的枝干了吧？我把篝火移远点。</p>' },
    { speaker: '陆悠悠', html: '<p>这个世界好多高到看不见顶的大树……真想知道它们长了几千还是几万年啊。</p>' },
    { speaker: '许泠朦', html: '<p>说到火，或许，一帆他只是迷路了呢？晚上看到这儿的火光，他就找回来了，对吧？</p>' },
    { speaker: '宋梦雨', html: '<p>没错。虽然他平日是不太靠谱。但现在这种情况，我不觉得他会抛下我们。</p>' },
    { speaker: '陆悠悠', html: '<p>先给他留一条鱼好了。明天罚他多钓两条～</p>' },
    { speaker: '叶唯安', html: '<p>实话说，一个人在这里生存挺困难，但我们是八个人，完全没有问——</p>' },
    { speaker: null, html: '<p>"咔嚓！"头顶又传来声响。</p>' },
    { speaker: '叶唯安', html: '<p>咳，接着说……总之，等他回来，八个人一起，一定能活下去，找到回家的——</p>' },
    { speaker: null, html: '<p>"嘭！"</p>' },
    { speaker: null, html: '<p>天上降下一个庞然大物，直接砸在了篝火上，火星四溅，众人躲闪不及！【轻微抖动】</p>' },
    { speaker: null, html: '<p>那一瞬间，火光映照出熟悉的人形轮廓，以及狰狞的面容。</p>' },
    { speaker: '我', html: '<p>一帆……？</p>' },
    { speaker: null, html: '<p>我们八个人终于再次聚齐了——以令人绝望的形式。</p>' },

  ],

  // 本片段无选项；播完后把 day 推进到 1，玩家正式进入第一天
  // 同时升起第一幕标题（第一幕在第 0 幕结束时自然衔接）
  afterPlayed: ()=>{
    if(typeof window.storyAdvanceDayToOne === 'function'){
      window.storyAdvanceDayToOne();
    }
    // 手动升起第一幕标题（第 0 幕正文最后一段之后）
    if(typeof window.showActTitle === 'function'){
      window.showActTitle('第一幕 分道扬镳');
    }
  },
};
